//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrySchemas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XSD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XSD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistrySchemas.Properties.XSD", typeof(XSD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;ZL_LIST&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;ZGLV&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;VERSION&quot;&gt;
        ///                &lt;xs:simpleType&gt;
        ///                  &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///                    &lt;xs:maxLength value=&quot;5&quot; /&gt;
        ///                    &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///                  &lt;/xs:restr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string C_reg {
            get {
                return ResourceManager.GetString("C_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;ZL_LIST&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;ZGLV&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;VERSION&quot;&gt;
        ///                &lt;xs:simpleType&gt;
        ///                  &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///                    &lt;xs:maxLength value=&quot;5&quot; /&gt;
        ///                    &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///                  &lt;/xs:restr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D_reg {
            get {
                return ResourceManager.GetString("D_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;ZL_LIST&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;ZGLV&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;VERSION&quot;&gt;
        ///                &lt;xs:simpleType&gt;
        ///                  &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///                    &lt;xs:maxLength value=&quot;5&quot; /&gt;
        ///                    &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///                  &lt;/xs:restr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H_reg {
            get {
                return ResourceManager.GetString("H_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;PERS_LIST&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;ZGLV&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;VERSION&quot;&gt;
        ///                &lt;xs:simpleType&gt;
        ///                  &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///                    &lt;xs:maxLength value=&quot;5&quot; /&gt;
        ///                    &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///                  &lt;/xs:res [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L_reg {
            get {
                return ResourceManager.GetString("L_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;ZL_LIST&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;ZGLV&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;VERSION&quot;&gt;
        ///                &lt;xs:simpleType&gt;
        ///                  &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///                    &lt;xs:maxLength value=&quot;5&quot; /&gt;
        ///                    &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///                  &lt;/xs:restr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T_reg {
            get {
                return ResourceManager.GetString("T_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;FLK_P&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;FNAME&quot;&gt;
        ///          &lt;xs:simpleType&gt;
        ///            &lt;xs:restriction base=&quot;xs:token&quot;&gt;
        ///              &lt;xs:maxLength value=&quot;24&quot; /&gt;
        ///              &lt;xs:minLength value=&quot;1&quot; /&gt;
        ///            &lt;/xs:restriction&gt;
        ///          &lt;/xs:simpleType&gt;
        ///        &lt;/xs:element&gt;
        ///        &lt;xs:element name=&quot;FNAME_I&quot;&gt;
        ///          &lt;xs:simpleType&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string V_reg {
            get {
                return ResourceManager.GetString("V_reg", resourceCulture);
            }
        }
    }
}
