//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace RegistrySchemas.DTO.C_reg {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ZL_LIST {
        
        private ZL_LISTZGLV zGLVField;
        
        private ZL_LISTSCHET sCHETField;
        
        private ZL_LISTZAP[] zAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZGLV ZGLV {
            get {
                return this.zGLVField;
            }
            set {
                this.zGLVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTSCHET SCHET {
            get {
                return this.sCHETField;
            }
            set {
                this.sCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZAP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAP[] ZAP {
            get {
                return this.zAPField;
            }
            set {
                this.zAPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZGLV {
        
        private string vERSIONField;
        
        private System.DateTime dATAField;
        
        private string fILENAMEField;
        
        private long sD_ZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long SD_Z {
            get {
                return this.sD_ZField;
            }
            set {
                this.sD_ZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTSCHET {
        
        private long cODEField;
        
        private string cODE_MOField;
        
        private long yEARField;
        
        private long mONTHField;
        
        private long yEAR_REPORTField;
        
        private long mONTH_REPORTField;
        
        private string nSCHETField;
        
        private System.DateTime dSCHETField;
        
        private string pLATField;
        
        private decimal sUMMAVField;
        
        private string cOMENTSField;
        
        private decimal sUMMAPField;
        
        private bool sUMMAPFieldSpecified;
        
        private decimal sANK_MEKField;
        
        private bool sANK_MEKFieldSpecified;
        
        private decimal sANK_MEEField;
        
        private bool sANK_MEEFieldSpecified;
        
        private decimal sANK_EKMPField;
        
        private bool sANK_EKMPFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_MO {
            get {
                return this.cODE_MOField;
            }
            set {
                this.cODE_MOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MONTH {
            get {
                return this.mONTHField;
            }
            set {
                this.mONTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long YEAR_REPORT {
            get {
                return this.yEAR_REPORTField;
            }
            set {
                this.yEAR_REPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MONTH_REPORT {
            get {
                return this.mONTH_REPORTField;
            }
            set {
                this.mONTH_REPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NSCHET {
            get {
                return this.nSCHETField;
            }
            set {
                this.nSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DSCHET {
            get {
                return this.dSCHETField;
            }
            set {
                this.dSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PLAT {
            get {
                return this.pLATField;
            }
            set {
                this.pLATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMMAV {
            get {
                return this.sUMMAVField;
            }
            set {
                this.sUMMAVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTS {
            get {
                return this.cOMENTSField;
            }
            set {
                this.cOMENTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMMAP {
            get {
                return this.sUMMAPField;
            }
            set {
                this.sUMMAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUMMAPSpecified {
            get {
                return this.sUMMAPFieldSpecified;
            }
            set {
                this.sUMMAPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_MEK {
            get {
                return this.sANK_MEKField;
            }
            set {
                this.sANK_MEKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_MEKSpecified {
            get {
                return this.sANK_MEKFieldSpecified;
            }
            set {
                this.sANK_MEKFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_MEE {
            get {
                return this.sANK_MEEField;
            }
            set {
                this.sANK_MEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_MEESpecified {
            get {
                return this.sANK_MEEFieldSpecified;
            }
            set {
                this.sANK_MEEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_EKMP {
            get {
                return this.sANK_EKMPField;
            }
            set {
                this.sANK_EKMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_EKMPSpecified {
            get {
                return this.sANK_EKMPFieldSpecified;
            }
            set {
                this.sANK_EKMPFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAP {
        
        private long n_ZAPField;
        
        private long pR_NOVField;
        
        private ZL_LISTZAPPACIENT pACIENTField;
        
        private ZL_LISTZAPZ_SL z_SLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long N_ZAP {
            get {
                return this.n_ZAPField;
            }
            set {
                this.n_ZAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PR_NOV {
            get {
                return this.pR_NOVField;
            }
            set {
                this.pR_NOVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPPACIENT PACIENT {
            get {
                return this.pACIENTField;
            }
            set {
                this.pACIENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SL Z_SL {
            get {
                return this.z_SLField;
            }
            set {
                this.z_SLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPPACIENT {
        
        private string iD_PACField;
        
        private long vPOLISField;
        
        private string sPOLISField;
        
        private string nPOLISField;
        
        private string sT_OKATOField;
        
        private string sMOField;
        
        private string sMO_OGRNField;
        
        private string sMO_OKField;
        
        private string sMO_NAMField;
        
        private long iNVField;
        
        private bool iNVFieldSpecified;
        
        private long mSEField;
        
        private bool mSEFieldSpecified;
        
        private string nOVORField;
        
        private long vNOV_DField;
        
        private bool vNOV_DFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ID_PAC {
            get {
                return this.iD_PACField;
            }
            set {
                this.iD_PACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VPOLIS {
            get {
                return this.vPOLISField;
            }
            set {
                this.vPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SPOLIS {
            get {
                return this.sPOLISField;
            }
            set {
                this.sPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NPOLIS {
            get {
                return this.nPOLISField;
            }
            set {
                this.nPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ST_OKATO {
            get {
                return this.sT_OKATOField;
            }
            set {
                this.sT_OKATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO {
            get {
                return this.sMOField;
            }
            set {
                this.sMOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_OGRN {
            get {
                return this.sMO_OGRNField;
            }
            set {
                this.sMO_OGRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_OK {
            get {
                return this.sMO_OKField;
            }
            set {
                this.sMO_OKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_NAM {
            get {
                return this.sMO_NAMField;
            }
            set {
                this.sMO_NAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long INV {
            get {
                return this.iNVField;
            }
            set {
                this.iNVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool INVSpecified {
            get {
                return this.iNVFieldSpecified;
            }
            set {
                this.iNVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MSE {
            get {
                return this.mSEField;
            }
            set {
                this.mSEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MSESpecified {
            get {
                return this.mSEFieldSpecified;
            }
            set {
                this.mSEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NOVOR {
            get {
                return this.nOVORField;
            }
            set {
                this.nOVORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VNOV_D {
            get {
                return this.vNOV_DField;
            }
            set {
                this.vNOV_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VNOV_DSpecified {
            get {
                return this.vNOV_DFieldSpecified;
            }
            set {
                this.vNOV_DFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SL {
        
        private long iDCASEField;
        
        private long uSL_OKField;
        
        private long vIDPOMField;
        
        private long fOR_POMField;
        
        private string nPR_MOField;
        
        private System.DateTime nPR_DATEField;
        
        private bool nPR_DATEFieldSpecified;
        
        private string lPUField;
        
        private System.DateTime dATE_Z_1Field;
        
        private System.DateTime dATE_Z_2Field;
        
        private long kD_ZField;
        
        private bool kD_ZFieldSpecified;
        
        private long[] vNOV_MField;
        
        private long rSLTField;
        
        private long iSHODField;
        
        private long[] oS_SLUCHField;
        
        private long vB_PField;
        
        private bool vB_PFieldSpecified;
        
        private long vB_P_IDCASEField;
        
        private bool vB_P_IDCASEFieldSpecified;
        
        private string vB_P_NSCHETField;
        
        private ZL_LISTZAPZ_SLSL slField;
        
        private long iDSPField;
        
        private decimal sUMVField;
        
        private long oPLATAField;
        
        private bool oPLATAFieldSpecified;
        
        private decimal sUMPField;
        
        private bool sUMPFieldSpecified;
        
        private ZL_LISTZAPZ_SLSANK[] sANKField;
        
        private decimal sANK_ITField;
        
        private bool sANK_ITFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDCASE {
            get {
                return this.iDCASEField;
            }
            set {
                this.iDCASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long USL_OK {
            get {
                return this.uSL_OKField;
            }
            set {
                this.uSL_OKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VIDPOM {
            get {
                return this.vIDPOMField;
            }
            set {
                this.vIDPOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long FOR_POM {
            get {
                return this.fOR_POMField;
            }
            set {
                this.fOR_POMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NPR_MO {
            get {
                return this.nPR_MOField;
            }
            set {
                this.nPR_MOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime NPR_DATE {
            get {
                return this.nPR_DATEField;
            }
            set {
                this.nPR_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NPR_DATESpecified {
            get {
                return this.nPR_DATEFieldSpecified;
            }
            set {
                this.nPR_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU {
            get {
                return this.lPUField;
            }
            set {
                this.lPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_Z_1 {
            get {
                return this.dATE_Z_1Field;
            }
            set {
                this.dATE_Z_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_Z_2 {
            get {
                return this.dATE_Z_2Field;
            }
            set {
                this.dATE_Z_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long KD_Z {
            get {
                return this.kD_ZField;
            }
            set {
                this.kD_ZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KD_ZSpecified {
            get {
                return this.kD_ZFieldSpecified;
            }
            set {
                this.kD_ZFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VNOV_M", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] VNOV_M {
            get {
                return this.vNOV_MField;
            }
            set {
                this.vNOV_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long RSLT {
            get {
                return this.rSLTField;
            }
            set {
                this.rSLTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ISHOD {
            get {
                return this.iSHODField;
            }
            set {
                this.iSHODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OS_SLUCH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] OS_SLUCH {
            get {
                return this.oS_SLUCHField;
            }
            set {
                this.oS_SLUCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VB_P {
            get {
                return this.vB_PField;
            }
            set {
                this.vB_PField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VB_PSpecified {
            get {
                return this.vB_PFieldSpecified;
            }
            set {
                this.vB_PFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VB_P_IDCASE {
            get {
                return this.vB_P_IDCASEField;
            }
            set {
                this.vB_P_IDCASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VB_P_IDCASESpecified {
            get {
                return this.vB_P_IDCASEFieldSpecified;
            }
            set {
                this.vB_P_IDCASEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VB_P_NSCHET {
            get {
                return this.vB_P_NSCHETField;
            }
            set {
                this.vB_P_NSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSL SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDSP {
            get {
                return this.iDSPField;
            }
            set {
                this.iDSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMV {
            get {
                return this.sUMVField;
            }
            set {
                this.sUMVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long OPLATA {
            get {
                return this.oPLATAField;
            }
            set {
                this.oPLATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OPLATASpecified {
            get {
                return this.oPLATAFieldSpecified;
            }
            set {
                this.oPLATAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMP {
            get {
                return this.sUMPField;
            }
            set {
                this.sUMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUMPSpecified {
            get {
                return this.sUMPFieldSpecified;
            }
            set {
                this.sUMPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SANK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSANK[] SANK {
            get {
                return this.sANKField;
            }
            set {
                this.sANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_IT {
            get {
                return this.sANK_ITField;
            }
            set {
                this.sANK_ITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_ITSpecified {
            get {
                return this.sANK_ITFieldSpecified;
            }
            set {
                this.sANK_ITFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSL {
        
        private string sL_IDField;
        
        private string lPU_1Field;
        
        private string pODRField;
        
        private long pROFILField;
        
        private long pROFIL_KField;
        
        private bool pROFIL_KFieldSpecified;
        
        private long dETField;
        
        private string p_CELField;
        
        private string nHISTORYField;
        
        private long p_PERField;
        
        private bool p_PERFieldSpecified;
        
        private System.DateTime dATE_1Field;
        
        private System.DateTime dATE_2Field;
        
        private long kdField;
        
        private bool kdFieldSpecified;
        
        private string dS0Field;
        
        private string dS1Field;
        
        private string[] dS2Field;
        
        private string[] dS3Field;
        
        private long c_ZABField;
        
        private bool c_ZABFieldSpecified;
        
        private long dS_ONKField;
        
        private long dnField;
        
        private bool dnFieldSpecified;
        
        private string[] cODE_MES1Field;
        
        private string cODE_MES2Field;
        
        private ZL_LISTZAPZ_SLSLNAPR[] nAPRField;
        
        private ZL_LISTZAPZ_SLSLCONS[] cONSField;
        
        private ZL_LISTZAPZ_SLSLONK_SL oNK_SLField;
        
        private ZL_LISTZAPZ_SLSLKSG_KPG kSG_KPGField;
        
        private long vkField;
        
        private bool vkFieldSpecified;
        
        private long rEABField;
        
        private bool rEABFieldSpecified;
        
        private long pRVSField;
        
        private string vERS_SPECField;
        
        private string iDDOKTField;
        
        private decimal eD_COLField;
        
        private decimal tARIFField;
        
        private decimal sUM_MField;
        
        private ZL_LISTZAPZ_SLSLUSL[] uSLField;
        
        private string cOMENTSLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SL_ID {
            get {
                return this.sL_IDField;
            }
            set {
                this.sL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU_1 {
            get {
                return this.lPU_1Field;
            }
            set {
                this.lPU_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PODR {
            get {
                return this.pODRField;
            }
            set {
                this.pODRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROFIL {
            get {
                return this.pROFILField;
            }
            set {
                this.pROFILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROFIL_K {
            get {
                return this.pROFIL_KField;
            }
            set {
                this.pROFIL_KField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PROFIL_KSpecified {
            get {
                return this.pROFIL_KFieldSpecified;
            }
            set {
                this.pROFIL_KFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DET {
            get {
                return this.dETField;
            }
            set {
                this.dETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string P_CEL {
            get {
                return this.p_CELField;
            }
            set {
                this.p_CELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NHISTORY {
            get {
                return this.nHISTORYField;
            }
            set {
                this.nHISTORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long P_PER {
            get {
                return this.p_PERField;
            }
            set {
                this.p_PERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool P_PERSpecified {
            get {
                return this.p_PERFieldSpecified;
            }
            set {
                this.p_PERFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_1 {
            get {
                return this.dATE_1Field;
            }
            set {
                this.dATE_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_2 {
            get {
                return this.dATE_2Field;
            }
            set {
                this.dATE_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long KD {
            get {
                return this.kdField;
            }
            set {
                this.kdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KDSpecified {
            get {
                return this.kdFieldSpecified;
            }
            set {
                this.kdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DS0 {
            get {
                return this.dS0Field;
            }
            set {
                this.dS0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DS1 {
            get {
                return this.dS1Field;
            }
            set {
                this.dS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DS2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] DS2 {
            get {
                return this.dS2Field;
            }
            set {
                this.dS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DS3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] DS3 {
            get {
                return this.dS3Field;
            }
            set {
                this.dS3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long C_ZAB {
            get {
                return this.c_ZABField;
            }
            set {
                this.c_ZABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool C_ZABSpecified {
            get {
                return this.c_ZABFieldSpecified;
            }
            set {
                this.c_ZABFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DS_ONK {
            get {
                return this.dS_ONKField;
            }
            set {
                this.dS_ONKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DN {
            get {
                return this.dnField;
            }
            set {
                this.dnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DNSpecified {
            get {
                return this.dnFieldSpecified;
            }
            set {
                this.dnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CODE_MES1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] CODE_MES1 {
            get {
                return this.cODE_MES1Field;
            }
            set {
                this.cODE_MES1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_MES2 {
            get {
                return this.cODE_MES2Field;
            }
            set {
                this.cODE_MES2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAPR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLNAPR[] NAPR {
            get {
                return this.nAPRField;
            }
            set {
                this.nAPRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CONS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLCONS[] CONS {
            get {
                return this.cONSField;
            }
            set {
                this.cONSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLONK_SL ONK_SL {
            get {
                return this.oNK_SLField;
            }
            set {
                this.oNK_SLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLKSG_KPG KSG_KPG {
            get {
                return this.kSG_KPGField;
            }
            set {
                this.kSG_KPGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VK {
            get {
                return this.vkField;
            }
            set {
                this.vkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VKSpecified {
            get {
                return this.vkFieldSpecified;
            }
            set {
                this.vkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long REAB {
            get {
                return this.rEABField;
            }
            set {
                this.rEABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REABSpecified {
            get {
                return this.rEABFieldSpecified;
            }
            set {
                this.rEABFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PRVS {
            get {
                return this.pRVSField;
            }
            set {
                this.pRVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VERS_SPEC {
            get {
                return this.vERS_SPECField;
            }
            set {
                this.vERS_SPECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IDDOKT {
            get {
                return this.iDDOKTField;
            }
            set {
                this.iDDOKTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ED_COL {
            get {
                return this.eD_COLField;
            }
            set {
                this.eD_COLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TARIF {
            get {
                return this.tARIFField;
            }
            set {
                this.tARIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUM_M {
            get {
                return this.sUM_MField;
            }
            set {
                this.sUM_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLUSL[] USL {
            get {
                return this.uSLField;
            }
            set {
                this.uSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTSL {
            get {
                return this.cOMENTSLField;
            }
            set {
                this.cOMENTSLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLNAPR {
        
        private System.DateTime nAPR_DATEField;
        
        private string nAPR_MOField;
        
        private long nAPR_VField;
        
        private long mET_ISSLField;
        
        private bool mET_ISSLFieldSpecified;
        
        private string nAPR_USLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime NAPR_DATE {
            get {
                return this.nAPR_DATEField;
            }
            set {
                this.nAPR_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NAPR_MO {
            get {
                return this.nAPR_MOField;
            }
            set {
                this.nAPR_MOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAPR_V {
            get {
                return this.nAPR_VField;
            }
            set {
                this.nAPR_VField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MET_ISSL {
            get {
                return this.mET_ISSLField;
            }
            set {
                this.mET_ISSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MET_ISSLSpecified {
            get {
                return this.mET_ISSLFieldSpecified;
            }
            set {
                this.mET_ISSLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NAPR_USL {
            get {
                return this.nAPR_USLField;
            }
            set {
                this.nAPR_USLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLCONS {
        
        private long pR_CONSField;
        
        private System.DateTime dT_CONSField;
        
        private bool dT_CONSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PR_CONS {
            get {
                return this.pR_CONSField;
            }
            set {
                this.pR_CONSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DT_CONS {
            get {
                return this.dT_CONSField;
            }
            set {
                this.dT_CONSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DT_CONSSpecified {
            get {
                return this.dT_CONSFieldSpecified;
            }
            set {
                this.dT_CONSFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLONK_SL {
        
        private long dS1_TField;
        
        private long sTADField;
        
        private bool sTADFieldSpecified;
        
        private long oNK_TField;
        
        private bool oNK_TFieldSpecified;
        
        private long oNK_NField;
        
        private bool oNK_NFieldSpecified;
        
        private long oNK_MField;
        
        private bool oNK_MFieldSpecified;
        
        private long mTSTZField;
        
        private bool mTSTZFieldSpecified;
        
        private decimal sODField;
        
        private bool sODFieldSpecified;
        
        private long k_FRField;
        
        private bool k_FRFieldSpecified;
        
        private decimal wEIField;
        
        private bool wEIFieldSpecified;
        
        private long hEIField;
        
        private bool hEIFieldSpecified;
        
        private decimal bSAField;
        
        private bool bSAFieldSpecified;
        
        private ZL_LISTZAPZ_SLSLONK_SLB_DIAG[] b_DIAGField;
        
        private ZL_LISTZAPZ_SLSLONK_SLB_PROT[] b_PROTField;
        
        private ZL_LISTZAPZ_SLSLONK_SLONK_USL[] oNK_USLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DS1_T {
            get {
                return this.dS1_TField;
            }
            set {
                this.dS1_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long STAD {
            get {
                return this.sTADField;
            }
            set {
                this.sTADField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool STADSpecified {
            get {
                return this.sTADFieldSpecified;
            }
            set {
                this.sTADFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ONK_T {
            get {
                return this.oNK_TField;
            }
            set {
                this.oNK_TField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ONK_TSpecified {
            get {
                return this.oNK_TFieldSpecified;
            }
            set {
                this.oNK_TFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ONK_N {
            get {
                return this.oNK_NField;
            }
            set {
                this.oNK_NField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ONK_NSpecified {
            get {
                return this.oNK_NFieldSpecified;
            }
            set {
                this.oNK_NFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long ONK_M {
            get {
                return this.oNK_MField;
            }
            set {
                this.oNK_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ONK_MSpecified {
            get {
                return this.oNK_MFieldSpecified;
            }
            set {
                this.oNK_MFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MTSTZ {
            get {
                return this.mTSTZField;
            }
            set {
                this.mTSTZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MTSTZSpecified {
            get {
                return this.mTSTZFieldSpecified;
            }
            set {
                this.mTSTZFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SOD {
            get {
                return this.sODField;
            }
            set {
                this.sODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SODSpecified {
            get {
                return this.sODFieldSpecified;
            }
            set {
                this.sODFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long K_FR {
            get {
                return this.k_FRField;
            }
            set {
                this.k_FRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool K_FRSpecified {
            get {
                return this.k_FRFieldSpecified;
            }
            set {
                this.k_FRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WEI {
            get {
                return this.wEIField;
            }
            set {
                this.wEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WEISpecified {
            get {
                return this.wEIFieldSpecified;
            }
            set {
                this.wEIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long HEI {
            get {
                return this.hEIField;
            }
            set {
                this.hEIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HEISpecified {
            get {
                return this.hEIFieldSpecified;
            }
            set {
                this.hEIFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BSA {
            get {
                return this.bSAField;
            }
            set {
                this.bSAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BSASpecified {
            get {
                return this.bSAFieldSpecified;
            }
            set {
                this.bSAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("B_DIAG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLONK_SLB_DIAG[] B_DIAG {
            get {
                return this.b_DIAGField;
            }
            set {
                this.b_DIAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("B_PROT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLONK_SLB_PROT[] B_PROT {
            get {
                return this.b_PROTField;
            }
            set {
                this.b_PROTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ONK_USL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLONK_SLONK_USL[] ONK_USL {
            get {
                return this.oNK_USLField;
            }
            set {
                this.oNK_USLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLONK_SLB_DIAG {
        
        private System.DateTime dIAG_DATEField;
        
        private long dIAG_TIPField;
        
        private long dIAG_CODEField;
        
        private long dIAG_RSLTField;
        
        private bool dIAG_RSLTFieldSpecified;
        
        private long rEC_RSLTField;
        
        private bool rEC_RSLTFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DIAG_DATE {
            get {
                return this.dIAG_DATEField;
            }
            set {
                this.dIAG_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DIAG_TIP {
            get {
                return this.dIAG_TIPField;
            }
            set {
                this.dIAG_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DIAG_CODE {
            get {
                return this.dIAG_CODEField;
            }
            set {
                this.dIAG_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DIAG_RSLT {
            get {
                return this.dIAG_RSLTField;
            }
            set {
                this.dIAG_RSLTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DIAG_RSLTSpecified {
            get {
                return this.dIAG_RSLTFieldSpecified;
            }
            set {
                this.dIAG_RSLTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long REC_RSLT {
            get {
                return this.rEC_RSLTField;
            }
            set {
                this.rEC_RSLTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool REC_RSLTSpecified {
            get {
                return this.rEC_RSLTFieldSpecified;
            }
            set {
                this.rEC_RSLTFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLONK_SLB_PROT {
        
        private long pROTField;
        
        private System.DateTime d_PROTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROT {
            get {
                return this.pROTField;
            }
            set {
                this.pROTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime D_PROT {
            get {
                return this.d_PROTField;
            }
            set {
                this.d_PROTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLONK_SLONK_USL {
        
        private long uSL_TIPField;
        
        private long hIR_TIPField;
        
        private bool hIR_TIPFieldSpecified;
        
        private long lEK_TIP_LField;
        
        private bool lEK_TIP_LFieldSpecified;
        
        private long lEK_TIP_VField;
        
        private bool lEK_TIP_VFieldSpecified;
        
        private ZL_LISTZAPZ_SLSLONK_SLONK_USLLEK_PR[] lEK_PRField;
        
        private long pPTRField;
        
        private bool pPTRFieldSpecified;
        
        private long lUCH_TIPField;
        
        private bool lUCH_TIPFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long USL_TIP {
            get {
                return this.uSL_TIPField;
            }
            set {
                this.uSL_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long HIR_TIP {
            get {
                return this.hIR_TIPField;
            }
            set {
                this.hIR_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HIR_TIPSpecified {
            get {
                return this.hIR_TIPFieldSpecified;
            }
            set {
                this.hIR_TIPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long LEK_TIP_L {
            get {
                return this.lEK_TIP_LField;
            }
            set {
                this.lEK_TIP_LField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LEK_TIP_LSpecified {
            get {
                return this.lEK_TIP_LFieldSpecified;
            }
            set {
                this.lEK_TIP_LFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long LEK_TIP_V {
            get {
                return this.lEK_TIP_VField;
            }
            set {
                this.lEK_TIP_VField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LEK_TIP_VSpecified {
            get {
                return this.lEK_TIP_VFieldSpecified;
            }
            set {
                this.lEK_TIP_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LEK_PR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLONK_SLONK_USLLEK_PR[] LEK_PR {
            get {
                return this.lEK_PRField;
            }
            set {
                this.lEK_PRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PPTR {
            get {
                return this.pPTRField;
            }
            set {
                this.pPTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PPTRSpecified {
            get {
                return this.pPTRFieldSpecified;
            }
            set {
                this.pPTRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long LUCH_TIP {
            get {
                return this.lUCH_TIPField;
            }
            set {
                this.lUCH_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LUCH_TIPSpecified {
            get {
                return this.lUCH_TIPFieldSpecified;
            }
            set {
                this.lUCH_TIPFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLONK_SLONK_USLLEK_PR {
        
        private string rEGNUMField;
        
        private string cODE_SHField;
        
        private System.DateTime[] dATE_INJField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string REGNUM {
            get {
                return this.rEGNUMField;
            }
            set {
                this.rEGNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_SH {
            get {
                return this.cODE_SHField;
            }
            set {
                this.cODE_SHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DATE_INJ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime[] DATE_INJ {
            get {
                return this.dATE_INJField;
            }
            set {
                this.dATE_INJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLKSG_KPG {
        
        private string n_KSGField;
        
        private long vER_KSGField;
        
        private long kSG_PGField;
        
        private string n_KPGField;
        
        private decimal kOEF_ZField;
        
        private decimal kOEF_UPField;
        
        private decimal bZTSZField;
        
        private decimal kOEF_DField;
        
        private decimal kOEF_UField;
        
        private decimal kOEF_PRField;
        
        private bool kOEF_PRFieldSpecified;
        
        private decimal kOEF_DLField;
        
        private bool kOEF_DLFieldSpecified;
        
        private string[] cRITField;
        
        private long sL_KField;
        
        private decimal iT_SLField;
        
        private bool iT_SLFieldSpecified;
        
        private ZL_LISTZAPZ_SLSLKSG_KPGSL_KOEF[] sL_KOEFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string N_KSG {
            get {
                return this.n_KSGField;
            }
            set {
                this.n_KSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VER_KSG {
            get {
                return this.vER_KSGField;
            }
            set {
                this.vER_KSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long KSG_PG {
            get {
                return this.kSG_PGField;
            }
            set {
                this.kSG_PGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string N_KPG {
            get {
                return this.n_KPGField;
            }
            set {
                this.n_KPGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_Z {
            get {
                return this.kOEF_ZField;
            }
            set {
                this.kOEF_ZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_UP {
            get {
                return this.kOEF_UPField;
            }
            set {
                this.kOEF_UPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal BZTSZ {
            get {
                return this.bZTSZField;
            }
            set {
                this.bZTSZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_D {
            get {
                return this.kOEF_DField;
            }
            set {
                this.kOEF_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_U {
            get {
                return this.kOEF_UField;
            }
            set {
                this.kOEF_UField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_PR {
            get {
                return this.kOEF_PRField;
            }
            set {
                this.kOEF_PRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KOEF_PRSpecified {
            get {
                return this.kOEF_PRFieldSpecified;
            }
            set {
                this.kOEF_PRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOEF_DL {
            get {
                return this.kOEF_DLField;
            }
            set {
                this.kOEF_DLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KOEF_DLSpecified {
            get {
                return this.kOEF_DLFieldSpecified;
            }
            set {
                this.kOEF_DLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CRIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] CRIT {
            get {
                return this.cRITField;
            }
            set {
                this.cRITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long SL_K {
            get {
                return this.sL_KField;
            }
            set {
                this.sL_KField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal IT_SL {
            get {
                return this.iT_SLField;
            }
            set {
                this.iT_SLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IT_SLSpecified {
            get {
                return this.iT_SLFieldSpecified;
            }
            set {
                this.iT_SLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SL_KOEF", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLKSG_KPGSL_KOEF[] SL_KOEF {
            get {
                return this.sL_KOEFField;
            }
            set {
                this.sL_KOEFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLKSG_KPGSL_KOEF {
        
        private long iDSLField;
        
        private decimal z_SLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDSL {
            get {
                return this.iDSLField;
            }
            set {
                this.iDSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Z_SL {
            get {
                return this.z_SLField;
            }
            set {
                this.z_SLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLUSL {
        
        private string iDSERVField;
        
        private string lPUField;
        
        private string lPU_1Field;
        
        private string pODRField;
        
        private long pROFILField;
        
        private string vID_VMEField;
        
        private long dETField;
        
        private System.DateTime dATE_INField;
        
        private System.DateTime dATE_OUTField;
        
        private string dsField;
        
        private string cODE_USLField;
        
        private decimal kOL_USLField;
        
        private decimal tARIFField;
        
        private decimal sUMV_USLField;
        
        private long pRVSField;
        
        private string cODE_MDField;
        
        private long nPLField;
        
        private bool nPLFieldSpecified;
        
        private string cOMENTUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IDSERV {
            get {
                return this.iDSERVField;
            }
            set {
                this.iDSERVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU {
            get {
                return this.lPUField;
            }
            set {
                this.lPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU_1 {
            get {
                return this.lPU_1Field;
            }
            set {
                this.lPU_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PODR {
            get {
                return this.pODRField;
            }
            set {
                this.pODRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROFIL {
            get {
                return this.pROFILField;
            }
            set {
                this.pROFILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VID_VME {
            get {
                return this.vID_VMEField;
            }
            set {
                this.vID_VMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DET {
            get {
                return this.dETField;
            }
            set {
                this.dETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_IN {
            get {
                return this.dATE_INField;
            }
            set {
                this.dATE_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_OUT {
            get {
                return this.dATE_OUTField;
            }
            set {
                this.dATE_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DS {
            get {
                return this.dsField;
            }
            set {
                this.dsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_USL {
            get {
                return this.cODE_USLField;
            }
            set {
                this.cODE_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KOL_USL {
            get {
                return this.kOL_USLField;
            }
            set {
                this.kOL_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TARIF {
            get {
                return this.tARIFField;
            }
            set {
                this.tARIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMV_USL {
            get {
                return this.sUMV_USLField;
            }
            set {
                this.sUMV_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PRVS {
            get {
                return this.pRVSField;
            }
            set {
                this.pRVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_MD {
            get {
                return this.cODE_MDField;
            }
            set {
                this.cODE_MDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NPL {
            get {
                return this.nPLField;
            }
            set {
                this.nPLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NPLSpecified {
            get {
                return this.nPLFieldSpecified;
            }
            set {
                this.nPLFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTU {
            get {
                return this.cOMENTUField;
            }
            set {
                this.cOMENTUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSANK {
        
        private string s_CODEField;
        
        private decimal s_SUMField;
        
        private long s_TIPField;
        
        private string[] sL_IDField;
        
        private long s_OSNField;
        
        private bool s_OSNFieldSpecified;
        
        private System.DateTime dATE_ACTField;
        
        private string nUM_ACTField;
        
        private string[] cODE_EXPField;
        
        private string s_COMField;
        
        private long s_ISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string S_CODE {
            get {
                return this.s_CODEField;
            }
            set {
                this.s_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal S_SUM {
            get {
                return this.s_SUMField;
            }
            set {
                this.s_SUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_TIP {
            get {
                return this.s_TIPField;
            }
            set {
                this.s_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SL_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] SL_ID {
            get {
                return this.sL_IDField;
            }
            set {
                this.sL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_OSN {
            get {
                return this.s_OSNField;
            }
            set {
                this.s_OSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool S_OSNSpecified {
            get {
                return this.s_OSNFieldSpecified;
            }
            set {
                this.s_OSNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_ACT {
            get {
                return this.dATE_ACTField;
            }
            set {
                this.dATE_ACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NUM_ACT {
            get {
                return this.nUM_ACTField;
            }
            set {
                this.nUM_ACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CODE_EXP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] CODE_EXP {
            get {
                return this.cODE_EXPField;
            }
            set {
                this.cODE_EXPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string S_COM {
            get {
                return this.s_COMField;
            }
            set {
                this.s_COMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_IST {
            get {
                return this.s_ISTField;
            }
            set {
                this.s_ISTField = value;
            }
        }
    }
}
