//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace RegistrySchemas.DTO.D_reg {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ZL_LIST {
        
        private ZL_LISTZGLV zGLVField;
        
        private ZL_LISTSCHET sCHETField;
        
        private ZL_LISTZAP[] zAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZGLV ZGLV {
            get {
                return this.zGLVField;
            }
            set {
                this.zGLVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTSCHET SCHET {
            get {
                return this.sCHETField;
            }
            set {
                this.sCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZAP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAP[] ZAP {
            get {
                return this.zAPField;
            }
            set {
                this.zAPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZGLV {
        
        private string vERSIONField;
        
        private System.DateTime dATAField;
        
        private string fILENAMEField;
        
        private long sD_ZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VERSION {
            get {
                return this.vERSIONField;
            }
            set {
                this.vERSIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long SD_Z {
            get {
                return this.sD_ZField;
            }
            set {
                this.sD_ZField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTSCHET {
        
        private long cODEField;
        
        private string cODE_MOField;
        
        private long yEARField;
        
        private long mONTHField;
        
        private long yEAR_REPORTField;
        
        private long mONTH_REPORTField;
        
        private string nSCHETField;
        
        private System.DateTime dSCHETField;
        
        private string pLATField;
        
        private decimal sUMMAVField;
        
        private string cOMENTSField;
        
        private decimal sUMMAPField;
        
        private bool sUMMAPFieldSpecified;
        
        private decimal sANK_MEKField;
        
        private bool sANK_MEKFieldSpecified;
        
        private decimal sANK_MEEField;
        
        private bool sANK_MEEFieldSpecified;
        
        private decimal sANK_EKMPField;
        
        private bool sANK_EKMPFieldSpecified;
        
        private string dISPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_MO {
            get {
                return this.cODE_MOField;
            }
            set {
                this.cODE_MOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long YEAR {
            get {
                return this.yEARField;
            }
            set {
                this.yEARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MONTH {
            get {
                return this.mONTHField;
            }
            set {
                this.mONTHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long YEAR_REPORT {
            get {
                return this.yEAR_REPORTField;
            }
            set {
                this.yEAR_REPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long MONTH_REPORT {
            get {
                return this.mONTH_REPORTField;
            }
            set {
                this.mONTH_REPORTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NSCHET {
            get {
                return this.nSCHETField;
            }
            set {
                this.nSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DSCHET {
            get {
                return this.dSCHETField;
            }
            set {
                this.dSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PLAT {
            get {
                return this.pLATField;
            }
            set {
                this.pLATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMMAV {
            get {
                return this.sUMMAVField;
            }
            set {
                this.sUMMAVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTS {
            get {
                return this.cOMENTSField;
            }
            set {
                this.cOMENTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMMAP {
            get {
                return this.sUMMAPField;
            }
            set {
                this.sUMMAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUMMAPSpecified {
            get {
                return this.sUMMAPFieldSpecified;
            }
            set {
                this.sUMMAPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_MEK {
            get {
                return this.sANK_MEKField;
            }
            set {
                this.sANK_MEKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_MEKSpecified {
            get {
                return this.sANK_MEKFieldSpecified;
            }
            set {
                this.sANK_MEKFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_MEE {
            get {
                return this.sANK_MEEField;
            }
            set {
                this.sANK_MEEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_MEESpecified {
            get {
                return this.sANK_MEEFieldSpecified;
            }
            set {
                this.sANK_MEEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_EKMP {
            get {
                return this.sANK_EKMPField;
            }
            set {
                this.sANK_EKMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_EKMPSpecified {
            get {
                return this.sANK_EKMPFieldSpecified;
            }
            set {
                this.sANK_EKMPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DISP {
            get {
                return this.dISPField;
            }
            set {
                this.dISPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAP {
        
        private long n_ZAPField;
        
        private long pR_NOVField;
        
        private ZL_LISTZAPPACIENT pACIENTField;
        
        private ZL_LISTZAPZ_SL z_SLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long N_ZAP {
            get {
                return this.n_ZAPField;
            }
            set {
                this.n_ZAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PR_NOV {
            get {
                return this.pR_NOVField;
            }
            set {
                this.pR_NOVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPPACIENT PACIENT {
            get {
                return this.pACIENTField;
            }
            set {
                this.pACIENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SL Z_SL {
            get {
                return this.z_SLField;
            }
            set {
                this.z_SLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPPACIENT {
        
        private string iD_PACField;
        
        private long vPOLISField;
        
        private string sPOLISField;
        
        private string nPOLISField;
        
        private string sT_OKATOField;
        
        private string sMOField;
        
        private string sMO_OGRNField;
        
        private string sMO_OKField;
        
        private string sMO_NAMField;
        
        private string nOVORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ID_PAC {
            get {
                return this.iD_PACField;
            }
            set {
                this.iD_PACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VPOLIS {
            get {
                return this.vPOLISField;
            }
            set {
                this.vPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SPOLIS {
            get {
                return this.sPOLISField;
            }
            set {
                this.sPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NPOLIS {
            get {
                return this.nPOLISField;
            }
            set {
                this.nPOLISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ST_OKATO {
            get {
                return this.sT_OKATOField;
            }
            set {
                this.sT_OKATOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO {
            get {
                return this.sMOField;
            }
            set {
                this.sMOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_OGRN {
            get {
                return this.sMO_OGRNField;
            }
            set {
                this.sMO_OGRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_OK {
            get {
                return this.sMO_OKField;
            }
            set {
                this.sMO_OKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SMO_NAM {
            get {
                return this.sMO_NAMField;
            }
            set {
                this.sMO_NAMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NOVOR {
            get {
                return this.nOVORField;
            }
            set {
                this.nOVORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SL {
        
        private long iDCASEField;
        
        private long vIDPOMField;
        
        private string lPUField;
        
        private long vBRField;
        
        private System.DateTime dATE_Z_1Field;
        
        private System.DateTime dATE_Z_2Field;
        
        private long p_OTKField;
        
        private long rSLT_DField;
        
        private long[] oS_SLUCHField;
        
        private ZL_LISTZAPZ_SLSL slField;
        
        private long iDSPField;
        
        private decimal sUMVField;
        
        private long oPLATAField;
        
        private bool oPLATAFieldSpecified;
        
        private decimal sUMPField;
        
        private bool sUMPFieldSpecified;
        
        private ZL_LISTZAPZ_SLSANK[] sANKField;
        
        private decimal sANK_ITField;
        
        private bool sANK_ITFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDCASE {
            get {
                return this.iDCASEField;
            }
            set {
                this.iDCASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VIDPOM {
            get {
                return this.vIDPOMField;
            }
            set {
                this.vIDPOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU {
            get {
                return this.lPUField;
            }
            set {
                this.lPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long VBR {
            get {
                return this.vBRField;
            }
            set {
                this.vBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_Z_1 {
            get {
                return this.dATE_Z_1Field;
            }
            set {
                this.dATE_Z_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_Z_2 {
            get {
                return this.dATE_Z_2Field;
            }
            set {
                this.dATE_Z_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long P_OTK {
            get {
                return this.p_OTKField;
            }
            set {
                this.p_OTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long RSLT_D {
            get {
                return this.rSLT_DField;
            }
            set {
                this.rSLT_DField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OS_SLUCH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] OS_SLUCH {
            get {
                return this.oS_SLUCHField;
            }
            set {
                this.oS_SLUCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSL SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDSP {
            get {
                return this.iDSPField;
            }
            set {
                this.iDSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMV {
            get {
                return this.sUMVField;
            }
            set {
                this.sUMVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long OPLATA {
            get {
                return this.oPLATAField;
            }
            set {
                this.oPLATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OPLATASpecified {
            get {
                return this.oPLATAFieldSpecified;
            }
            set {
                this.oPLATAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMP {
            get {
                return this.sUMPField;
            }
            set {
                this.sUMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUMPSpecified {
            get {
                return this.sUMPFieldSpecified;
            }
            set {
                this.sUMPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SANK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSANK[] SANK {
            get {
                return this.sANKField;
            }
            set {
                this.sANKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SANK_IT {
            get {
                return this.sANK_ITField;
            }
            set {
                this.sANK_ITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SANK_ITSpecified {
            get {
                return this.sANK_ITFieldSpecified;
            }
            set {
                this.sANK_ITFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSL {
        
        private string sL_IDField;
        
        private string lPU_1Field;
        
        private string pODRField;
        
        private long pROFILField;
        
        private string nHISTORYField;
        
        private System.DateTime dATE_1Field;
        
        private System.DateTime dATE_2Field;
        
        private string dS1Field;
        
        private long dS1_PRField;
        
        private bool dS1_PRFieldSpecified;
        
        private long dS_ONKField;
        
        private long pR_D_NField;
        
        private bool pR_D_NFieldSpecified;
        
        private ZL_LISTZAPZ_SLSLDS2_N[] dS2_NField;
        
        private ZL_LISTZAPZ_SLSLNAZ[] nAZField;
        
        private long pRVSField;
        
        private string vERS_SPECField;
        
        private string iDDOKTField;
        
        private decimal eD_COLField;
        
        private decimal tARIFField;
        
        private decimal sUM_MField;
        
        private ZL_LISTZAPZ_SLSLUSL[] uSLField;
        
        private string cOMENTSLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SL_ID {
            get {
                return this.sL_IDField;
            }
            set {
                this.sL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU_1 {
            get {
                return this.lPU_1Field;
            }
            set {
                this.lPU_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PODR {
            get {
                return this.pODRField;
            }
            set {
                this.pODRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROFIL {
            get {
                return this.pROFILField;
            }
            set {
                this.pROFILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NHISTORY {
            get {
                return this.nHISTORYField;
            }
            set {
                this.nHISTORYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_1 {
            get {
                return this.dATE_1Field;
            }
            set {
                this.dATE_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_2 {
            get {
                return this.dATE_2Field;
            }
            set {
                this.dATE_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DS1 {
            get {
                return this.dS1Field;
            }
            set {
                this.dS1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DS1_PR {
            get {
                return this.dS1_PRField;
            }
            set {
                this.dS1_PRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DS1_PRSpecified {
            get {
                return this.dS1_PRFieldSpecified;
            }
            set {
                this.dS1_PRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DS_ONK {
            get {
                return this.dS_ONKField;
            }
            set {
                this.dS_ONKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PR_D_N {
            get {
                return this.pR_D_NField;
            }
            set {
                this.pR_D_NField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PR_D_NSpecified {
            get {
                return this.pR_D_NFieldSpecified;
            }
            set {
                this.pR_D_NFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DS2_N", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLDS2_N[] DS2_N {
            get {
                return this.dS2_NField;
            }
            set {
                this.dS2_NField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NAZ", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLNAZ[] NAZ {
            get {
                return this.nAZField;
            }
            set {
                this.nAZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PRVS {
            get {
                return this.pRVSField;
            }
            set {
                this.pRVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string VERS_SPEC {
            get {
                return this.vERS_SPECField;
            }
            set {
                this.vERS_SPECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IDDOKT {
            get {
                return this.iDDOKTField;
            }
            set {
                this.iDDOKTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ED_COL {
            get {
                return this.eD_COLField;
            }
            set {
                this.eD_COLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TARIF {
            get {
                return this.tARIFField;
            }
            set {
                this.tARIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUM_M {
            get {
                return this.sUM_MField;
            }
            set {
                this.sUM_MField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("USL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZL_LISTZAPZ_SLSLUSL[] USL {
            get {
                return this.uSLField;
            }
            set {
                this.uSLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTSL {
            get {
                return this.cOMENTSLField;
            }
            set {
                this.cOMENTSLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLDS2_N {
        
        private string dS2Field;
        
        private long dS2_PRField;
        
        private bool dS2_PRFieldSpecified;
        
        private long pR_DS2_NField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string DS2 {
            get {
                return this.dS2Field;
            }
            set {
                this.dS2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long DS2_PR {
            get {
                return this.dS2_PRField;
            }
            set {
                this.dS2_PRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DS2_PRSpecified {
            get {
                return this.dS2_PRFieldSpecified;
            }
            set {
                this.dS2_PRFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PR_DS2_N {
            get {
                return this.pR_DS2_NField;
            }
            set {
                this.pR_DS2_NField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLNAZ {
        
        private long nAZ_NField;
        
        private long nAZ_RField;
        
        private long nAZ_SPField;
        
        private bool nAZ_SPFieldSpecified;
        
        private long nAZ_VField;
        
        private bool nAZ_VFieldSpecified;
        
        private string nAZ_USLField;
        
        private System.DateTime nAPR_DATEField;
        
        private bool nAPR_DATEFieldSpecified;
        
        private string nAPR_MOField;
        
        private long nAZ_PMPField;
        
        private bool nAZ_PMPFieldSpecified;
        
        private long nAZ_PKField;
        
        private bool nAZ_PKFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_N {
            get {
                return this.nAZ_NField;
            }
            set {
                this.nAZ_NField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_R {
            get {
                return this.nAZ_RField;
            }
            set {
                this.nAZ_RField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_SP {
            get {
                return this.nAZ_SPField;
            }
            set {
                this.nAZ_SPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAZ_SPSpecified {
            get {
                return this.nAZ_SPFieldSpecified;
            }
            set {
                this.nAZ_SPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_V {
            get {
                return this.nAZ_VField;
            }
            set {
                this.nAZ_VField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAZ_VSpecified {
            get {
                return this.nAZ_VFieldSpecified;
            }
            set {
                this.nAZ_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NAZ_USL {
            get {
                return this.nAZ_USLField;
            }
            set {
                this.nAZ_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime NAPR_DATE {
            get {
                return this.nAPR_DATEField;
            }
            set {
                this.nAPR_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAPR_DATESpecified {
            get {
                return this.nAPR_DATEFieldSpecified;
            }
            set {
                this.nAPR_DATEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NAPR_MO {
            get {
                return this.nAPR_MOField;
            }
            set {
                this.nAPR_MOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_PMP {
            get {
                return this.nAZ_PMPField;
            }
            set {
                this.nAZ_PMPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAZ_PMPSpecified {
            get {
                return this.nAZ_PMPFieldSpecified;
            }
            set {
                this.nAZ_PMPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long NAZ_PK {
            get {
                return this.nAZ_PKField;
            }
            set {
                this.nAZ_PKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAZ_PKSpecified {
            get {
                return this.nAZ_PKFieldSpecified;
            }
            set {
                this.nAZ_PKFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSLUSL {
        
        private string iDSERVField;
        
        private string lPUField;
        
        private string lPU_1Field;
        
        private string pODRField;
        
        private long pROFILField;
        
        private System.DateTime dATE_INField;
        
        private System.DateTime dATE_OUTField;
        
        private long p_OTKField;
        
        private string cODE_USLField;
        
        private decimal tARIFField;
        
        private decimal sUMV_USLField;
        
        private long pRVSField;
        
        private bool pRVSFieldSpecified;
        
        private string cODE_MDField;
        
        private string cOMENTUField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IDSERV {
            get {
                return this.iDSERVField;
            }
            set {
                this.iDSERVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU {
            get {
                return this.lPUField;
            }
            set {
                this.lPUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string LPU_1 {
            get {
                return this.lPU_1Field;
            }
            set {
                this.lPU_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string PODR {
            get {
                return this.pODRField;
            }
            set {
                this.pODRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PROFIL {
            get {
                return this.pROFILField;
            }
            set {
                this.pROFILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_IN {
            get {
                return this.dATE_INField;
            }
            set {
                this.dATE_INField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_OUT {
            get {
                return this.dATE_OUTField;
            }
            set {
                this.dATE_OUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long P_OTK {
            get {
                return this.p_OTKField;
            }
            set {
                this.p_OTKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_USL {
            get {
                return this.cODE_USLField;
            }
            set {
                this.cODE_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TARIF {
            get {
                return this.tARIFField;
            }
            set {
                this.tARIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SUMV_USL {
            get {
                return this.sUMV_USLField;
            }
            set {
                this.sUMV_USLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long PRVS {
            get {
                return this.pRVSField;
            }
            set {
                this.pRVSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PRVSSpecified {
            get {
                return this.pRVSFieldSpecified;
            }
            set {
                this.pRVSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CODE_MD {
            get {
                return this.cODE_MDField;
            }
            set {
                this.cODE_MDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMENTU {
            get {
                return this.cOMENTUField;
            }
            set {
                this.cOMENTUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZL_LISTZAPZ_SLSANK {
        
        private string s_CODEField;
        
        private decimal s_SUMField;
        
        private long s_TIPField;
        
        private string[] sL_IDField;
        
        private long s_OSNField;
        
        private bool s_OSNFieldSpecified;
        
        private System.DateTime dATE_ACTField;
        
        private string nUM_ACTField;
        
        private string[] cODE_EXPField;
        
        private string s_COMField;
        
        private long s_ISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string S_CODE {
            get {
                return this.s_CODEField;
            }
            set {
                this.s_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal S_SUM {
            get {
                return this.s_SUMField;
            }
            set {
                this.s_SUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_TIP {
            get {
                return this.s_TIPField;
            }
            set {
                this.s_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SL_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] SL_ID {
            get {
                return this.sL_IDField;
            }
            set {
                this.sL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_OSN {
            get {
                return this.s_OSNField;
            }
            set {
                this.s_OSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool S_OSNSpecified {
            get {
                return this.s_OSNFieldSpecified;
            }
            set {
                this.s_OSNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DATE_ACT {
            get {
                return this.dATE_ACTField;
            }
            set {
                this.dATE_ACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NUM_ACT {
            get {
                return this.nUM_ACTField;
            }
            set {
                this.nUM_ACTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CODE_EXP", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string[] CODE_EXP {
            get {
                return this.cODE_EXPField;
            }
            set {
                this.cODE_EXPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string S_COM {
            get {
                return this.s_COMField;
            }
            set {
                this.s_COMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long S_IST {
            get {
                return this.s_ISTField;
            }
            set {
                this.s_ISTField = value;
            }
        }
    }
}
