//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace RegistrySchemas.DTO.V_reg {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FLK_P {
        
        private string fNAMEField;
        
        private string fNAME_IField;
        
        private FLK_PPR[] prField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string FNAME {
            get {
                return this.fNAMEField;
            }
            set {
                this.fNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string FNAME_I {
            get {
                return this.fNAME_IField;
            }
            set {
                this.fNAME_IField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FLK_PPR[] PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FLK_PPR {
        
        private string oSHIBField;
        
        private string iM_POLField;
        
        private string zN_POLField;
        
        private string nSCHETField;
        
        private string bAS_ELField;
        
        private string n_ZAPField;
        
        private string iD_PACField;
        
        private long iDCASEField;
        
        private bool iDCASEFieldSpecified;
        
        private string sL_IDField;
        
        private string iDSERVField;
        
        private string cOMMENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string OSHIB {
            get {
                return this.oSHIBField;
            }
            set {
                this.oSHIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IM_POL {
            get {
                return this.iM_POLField;
            }
            set {
                this.iM_POLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ZN_POL {
            get {
                return this.zN_POLField;
            }
            set {
                this.zN_POLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string NSCHET {
            get {
                return this.nSCHETField;
            }
            set {
                this.nSCHETField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string BAS_EL {
            get {
                return this.bAS_ELField;
            }
            set {
                this.bAS_ELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string N_ZAP {
            get {
                return this.n_ZAPField;
            }
            set {
                this.n_ZAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ID_PAC {
            get {
                return this.iD_PACField;
            }
            set {
                this.iD_PACField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IDCASE {
            get {
                return this.iDCASEField;
            }
            set {
                this.iDCASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDCASESpecified {
            get {
                return this.iDCASEFieldSpecified;
            }
            set {
                this.iDCASEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SL_ID {
            get {
                return this.sL_IDField;
            }
            set {
                this.sL_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string IDSERV {
            get {
                return this.iDSERVField;
            }
            set {
                this.iDSERVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string COMMENT {
            get {
                return this.cOMMENTField;
            }
            set {
                this.cOMMENTField = value;
            }
        }
    }
}
